name = "bishare-relay"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
MAX_FILE_SIZE = "2147483648"   # 2GB
EXPIRY_HOURS = "24"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bishare-transfers"

[[kv_namespaces]]
binding = "ROOMS"
id = "162783126bb448518355623999a7d85f"

[placement]
mode = "smart"

[triggers]
crons = ["0 * * * *"]
